# Generated by Django 4.0.2 on 2022-03-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='county',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='estate',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='town',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='county',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='estate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='town',
        ),
    ]
