# Generated by Django 4.0.2 on 2022-03-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.counties'),
        ),
        migrations.AddField(
            model_name='customer',
            name='estate',
            field=models.CharField(blank=True, max_length=106, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
