# Generated by Django 4.0.2 on 2023-02-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='crop_icon',
            field=models.ImageField(blank=True, null=True, upload_to='crops-icons/'),
        ),
    ]
