# Generated by Django 4.2.7 on 2023-11-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=156, verbose_name="product name"),
                ),
                (
                    "quantity",
                    models.FloatField(default=0.0, help_text="Number of Kgs available"),
                ),
                ("image", models.ImageField(upload_to="products/%y%m/%d")),
                ("price", models.FloatField(default=0.0, verbose_name="price")),
                (
                    "is_verified",
                    models.BooleanField(default=True, verbose_name="is_verified"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "on_stock",
                    models.BooleanField(default=True, verbose_name="on stock"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.farmproductcategory",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.farmer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Farm Products",
            },
        ),
    ]
