# Generated by Django 4.0.2 on 2022-03-14 04:53

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='bio',
            field=models.TextField(blank=True, default='I am an energetic and enthusiatic farmer who can help you grow your business,\n     Contact me today for quality and fresh deriveries.', null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='default.png'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bio',
            field=models.TextField(blank=True, default='I am an energetic and enthusiatic farmer who can help you grow your business,\n     Contact me today for quality and fresh deriveries.', null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='default.png'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='bio',
            field=models.TextField(blank=True, default='I am an energetic and enthusiatic farmer who can help you grow your business,\n     Contact me today for quality and fresh deriveries.', null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='derivery',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Paid', max_length=10, null=True, verbose_name='derivery'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Ameture', 'Ameture'), ('Pro', 'Pro')], default='Beginner', max_length=14, null=True, verbose_name='delivery level'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='default.png'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='response',
            field=models.ForeignKey(blank=True, default='2 hrs', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.responsetime'),
        ),
    ]
