# Generated by Django 4.0.2 on 2022-03-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_administrator_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='derivery',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Paid', 'Paid')], default=2, max_length=10, null=True, verbose_name='derivery'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Ameture', 'Ameture'), ('Pro', 'Pro')], default=1, max_length=14, null=True, verbose_name='delivery level'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='response',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.responsetime'),
        ),
    ]
