# Generated by Django 4.0.2 on 2022-03-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_dealer_derivery_alter_dealer_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='derivery',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=10, null=True, verbose_name='derivery'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Ameture', 'Ameture'), ('Pro', 'Pro')], default='Beginner', max_length=14, null=True, verbose_name='delivery level'),
        ),
    ]
